{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "269041a6",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2023-10-25T06:24:29.573603Z",
     "start_time": "2023-10-25T06:24:17.948390Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on all addresses.\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      " * Running on http://172.30.1.45:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [25/Oct/2023 15:24:21] \"POST /ing_predict HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "import io\n",
    "import torch\n",
    "from PIL import Image\n",
    "import json\n",
    "import flask\n",
    "from flask import Flask, request, jsonify\n",
    "import pickle\n",
    "from torchvision import transforms\n",
    "from torchvision.models import resnet50\n",
    "import base64\n",
    "import ast\n",
    "import numpy as np\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "from sklearn.preprocessing import MultiLabelBinarizer\n",
    "import pandas as pd\n",
    "from torchvision.datasets import ImageFolder\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "# device 설정\n",
    "device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
    "\n",
    "# 데이터 변환 모듈 로드 (검증 데이터 용으로)\n",
    "transform = transforms.Compose(\n",
    "    [\n",
    "        transforms.Resize([224, 224]),\n",
    "        transforms.ToTensor(),\n",
    "        transforms.Normalize(mean=[0.485, 0.456, 0.406],\n",
    "                             std=[0.229, 0.224, 0.225])\n",
    "    ]\n",
    ")\n",
    "\n",
    "\"\"\"recipe.csv 불러오고 필요한 list 생성\"\"\"\n",
    "df = pd.read_csv('recipe.csv', encoding='cp949')\n",
    "cook_list = [] # 레시피 목록\n",
    "ingredients = [] # 레시피별 재료 목록\n",
    "all_ingredients = {} # 전체 재료 목록\n",
    "for idx, row in df.iterrows(): # pandas dataframe의 한 행씩 가져옴. idx=행 번호(0부터), row=행의 data\n",
    "    cook_list.append(row['메뉴'])\n",
    "    ingredient_map = {}\n",
    "    for val in ast.literal_eval(row['재료']):\n",
    "        ingredient_map[val] = 1\n",
    "        all_ingredients[val] = 1\n",
    "    ingredients.append(ingredient_map)\n",
    "\n",
    "# cook_list 정렬(success에 필요)\n",
    "cook_list.sort()\n",
    "\n",
    "# 재료의 카테고리 번호를 저장 (중복X)(recommend에 필요)\n",
    "category_index = {} \n",
    "for idx, val in enumerate(sorted(all_ingredients.keys())):\n",
    "    category_index[val] = idx\n",
    "\n",
    "matrix = []\n",
    "for ingred_map in ingredients:\n",
    "    tmp = []\n",
    "    for val in ingred_map.keys(): \n",
    "        tmp.append(category_index[val])\n",
    "    matrix.append(tmp)\n",
    "\n",
    "# 0, 1 행렬로 변환\n",
    "mlb = MultiLabelBinarizer()\n",
    "multi_hot_matrix = mlb.fit_transform(matrix)\n",
    "\n",
    "\"\"\"식재료 데이터 불러오기\"\"\"\n",
    "val_data_dir = '../ing_val4'\n",
    "val_dataset = ImageFolder(val_data_dir)\n",
    "class_names = val_dataset.classes\n",
    "\n",
    "\"\"\"success 모델 로딩\"\"\"\n",
    "# num_classes는 학습된 레시피의 개수\n",
    "success_model = resnet50(num_classes = len(cook_list))\n",
    "success_weights_path = \"resnet50.pth\"\n",
    "success_model.load_state_dict(torch.load(success_weights_path, map_location=torch.device('cpu')))\n",
    "success_model.eval()\n",
    "\n",
    "\"\"\"ing_predict 모델 로딩\"\"\"\n",
    "# num_classes는 학습된 식재료 개수\n",
    "ing_model = resnet50(num_classes = 69)\n",
    "ing_weights_path = \"ing_resnet50.pth\"\n",
    "ing_model.load_state_dict(torch.load(ing_weights_path, map_location=torch.device('cpu')))\n",
    "ing_model.eval()\n",
    "\n",
    "\"\"\"완성 사진 성공 여부 출력해주는 API\"\"\"\n",
    "@app.route('/success', methods=['POST'])\n",
    "def predict():\n",
    "    if request.method == 'POST':\n",
    "        data = flask.request.data.decode('utf-8')\n",
    "        s = io.StringIO(data)\n",
    "        js = json.load(s)\n",
    "\n",
    "        label = js['label'] # 사용자가 만든 음식 라벨\n",
    "        image = Image.open(io.BytesIO(base64.b64decode(js['image'].split(',')[-1]))).convert('RGB')\n",
    "        input_data = transform(image).unsqueeze(0).to(device)\n",
    "\n",
    "        outputs = success_model(input_data)\n",
    "        top4_op = outputs.topk(4, dim=-1)[1][0].numpy().tolist()\n",
    "        \n",
    "        # 모델이 예측한것과 레시피의 음식이 일치하는지 확인 (음식 라벨과 모델 예측값이 일치하는지 확인)    \n",
    "        success_res = False\n",
    "        for i in top4_op:\n",
    "            if cook_list[i] == label:\n",
    "                success_res = True\n",
    "        \n",
    "        result = {\n",
    "            \"results\" : success_res\n",
    "        }\n",
    "\n",
    "        return flask.Response(\n",
    "            response=json.dumps(result, ensure_ascii=False, indent='\\t'),\n",
    "            status=200,\n",
    "            mimetype=\"application/json\"\n",
    "        )\n",
    "    \n",
    "\"\"\"레시피 추천해주는 API\"\"\"\n",
    "@app.route('/recommend', methods=['POST'])\n",
    "def recommend():\n",
    "    if request.method == 'POST':\n",
    "        data = flask.request.data.decode('utf-8')\n",
    "        s = io.StringIO(data)\n",
    "        js = json.load(s)\n",
    "        \n",
    "        ing = js['user_ing']\n",
    "        \n",
    "        all_ing_len = len(list(all_ingredients.keys()))\n",
    "        \n",
    "        user_matrix = [0 for i in range(all_ing_len)]\n",
    "        for i in ing:\n",
    "            user_matrix[i]=1\n",
    "        \n",
    "        similarity_scores = cosine_similarity([user_matrix], multi_hot_matrix)[0]\n",
    "        \n",
    "        idxs = np.argsort(similarity_scores)[::-1]\n",
    "\n",
    "        # 상위 5개 점수\n",
    "        top5_scores = similarity_scores[idxs][:5]\n",
    "        top5_idxs = idxs[:5] # 상위 5개 인덱스 번호\n",
    "        top5_recipe = [] # 상위 5개 매칭 레시피\n",
    "\n",
    "        for id in top5_idxs:\n",
    "            top5_recipe.append(cook_list[id])\n",
    "        \n",
    "        result = {\n",
    "            \"recipe\" : top5_recipe\n",
    "        }\n",
    "        \n",
    "        return flask.Response(\n",
    "            response=json.dumps(result, ensure_ascii=False, indent='\\t'),\n",
    "            status=200,\n",
    "            mimetype=\"application/json\"\n",
    "        )\n",
    "\n",
    "\"\"\"OD 식재료 라벨 출력하는 API\"\"\"\n",
    "@app.route('/ing_predict', methods=['POST'])\n",
    "def predict_ing():\n",
    "    if request.method == 'POST':\n",
    "        data = flask.request.data.decode('utf-8')\n",
    "        s = io.StringIO(data)\n",
    "        js = json.load(s)\n",
    "\n",
    "        image = Image.open(io.BytesIO(base64.b64decode(js['image'].split(',')[-1]))).convert('RGB')\n",
    "        input_data = transform(image).unsqueeze(0).to(device)\n",
    "\n",
    "        outputs = ing_model(input_data)\n",
    "        label_pre = outputs.topk(1, dim=-1)[1][0]\n",
    "        \n",
    "        result = {\n",
    "            \"result\" : class_names[label_pre]\n",
    "        }\n",
    "        \n",
    "        return flask.Response(\n",
    "            response=json.dumps(result, ensure_ascii=False, indent='\\t'),\n",
    "            status=200,\n",
    "            mimetype=\"application/json\"\n",
    "        )\n",
    "        \n",
    "if __name__ == '__main__':\n",
    "    app.run(host='0.0.0.0', port=5000)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
